image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .m2/
    - .gradle/

stages:
  - deploy
  - deploy2

before_script:
  - chmod +x gradlew
  - echo $KEY_FILE_B64 | base64 -d > app/key.keystore
  - echo $SERVICE_ACCOUNT_JSON > app/service-account.json
  - echo "signing.storePassword=$KEY_STORE_PASSWORD" >> local.properties
  - echo "signing.storeAlias=$RELEASE_KEY_ALIAS" >> local.properties
  - echo "signing.keyPassword=$RELEASE_KEY_PASSWORD" >> local.properties
  - eval "$DEBUGGING_STATEMENT_BEFORE"

after_script:
  - rm app/service-account.json
  - rm app/key.keystore
  - rm local.properties
  - eval "$DEBUGGING_STATEMENT_AFTER"

deploy_google_play:
  stage: deploy
  script:
    - ./gradlew publishReleaseBundle
  artifacts:
    when: always
    paths:
      - app/build/outputs/bundle/release/*.aab
      - outputs/release_notes.txt
  only:
    - tags

deploy_gitlab:
  stage: deploy2
  needs: [ "build" ]
  image: inetprocess/gitlab-release
  script:
    - ./gradlew assembleRelease
    - gitlab-release --message "$CI_COMMIT_TAG" app/build/outputs/apk/release/app-release.apk
  only:
    - tags

deploy_firebase:
  stage: deploy2
  needs: [ "deploy_google_play" ]
  image: node
  script:
    - npm install -g firebase-tools
    - git tag -l --format='%(contents)' "$CI_COMMIT_TAG" > outputs/release_notes.txt
    - firebase appdistribution:distribute app/build/outputs/bundle/release/app-release.aab --token "$FIREBASE_CLI_TOKEN" --app "$FIREBASE_APP_ID" --release-notes-file "outputs/release_notes.txt" --groups "$FIREBASE_TESTER_GROUPS"
  only:
    - tags
