image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .m2/
    - .gradle/

stages:
  - test
  - build
  - deploy

before_script:
  - chmod +x gradlew
  - echo $KEY_FILE_B64 | base64 --decode > key.keystore
  - cp key.keystore app/
  - echo "signing.storePassword=$KEY_STORE_PASSWORD" >> local.properties
  - echo "signing.storeAlias=$RELEASE_KEY_ALIAS" >> local.properties
  - echo "signing.keyPassword=$RELEASE_KEY_PASSWORD" >> local.properties

after_script:
  - rm key.keystore
  - rm app/key.keystore
  - rm local.properties

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - app/build/reports/

build:
  stage: build
  script:
    - ./gradlew bundle
  artifacts:
    when: always
    paths:
      - app/build/outputs/bundle/release/*.aab
      - app/build/outputs/bundle/debug/*.aab
  only:
    - tags