image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .m2/
    - .gradle/

stages:
  - test
  - build
  - deploy

before_script:
  - chmod +x gradlew
  - echo $KEY_FILE_B64 | base64 --decode > app/key.keystore
  - echo $SERVICE_ACCOUNT_JSON > app/service-account.json
  - echo "signing.storePassword=$KEY_STORE_PASSWORD" >> local.properties
  - echo "signing.storeAlias=$RELEASE_KEY_ALIAS" >> local.properties
  - echo "signing.keyPassword=$RELEASE_KEY_PASSWORD" >> local.properties
  - shasum app/service-account.json

after_script:
  - rm app/service-account.json
  - rm app/key.keystore
  - rm local.properties

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - app/build/reports/

build:
  stage: build
  script:
    - ./gradlew publishReleaseBundle
  artifacts:
    when: always
    paths:
      - app/build/outputs/bundle/release/*.aab
  only:
    - tags