package de.crysxd.octoapp.base.gcode

class PrusaSlicerGcodeInterpreter : GcodeInterpreter() {
    override fun canInterpretFile(content: String) = content.contains("; generated by PrusaSlicer")
    override fun isLayerChange(line: String) = line.startsWith(";AFTER_LAYER_CHANGE", true)
}