version: '3.7'

services:
  octoprint:
    image: octoprint/octoprint
    ports:
      - 5001:5000
      - 5000:5000
    # devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./data:/octoprint/octoprint

volumes:
  octoprint:
